all:
  hosts:
    cp1:
      ansible_host: 51.250.87.170
      ip: 192.168.10.16
      ansible_user: ubuntu
    node1:
      ansible_host: 84.201.144.15
      ip: 192.168.12.21
      ansible_user: ubuntu
    node2:
      ansible_host: 158.160.3.183
      ip: 192.168.11.27
      ansible_user: ubuntu
    node3:
      ansible_host: 158.160.44.21
      ip: 192.168.10.18
      ansible_user: ubuntu
  children:
    kube_control_plane:
      hosts:
        cp1:
    kube_node:
      hosts:
        node1:
        node2:
        node3:
    etcd:
      hosts:
        cp1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
